# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_Back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='format',
        ),
    ]
