# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_Back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
