# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_Back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
